spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'kuba'
  jpa:
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        jdbc:
          lob:
            non_contextual_creation: true
storage:
  app:
    jwtSecret: 'KubaSecretKey'
    jwtExpirationMs: 86400000
